name: new_app
description: A fashion outfit matching app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  sqflite: ^2.3.0
  path: ^1.8.3
  image_picker: ^1.0.4
  provider: ^6.1.1
  tflite_flutter: ^0.10.4
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  http: ^1.1.0
  firebase_core: ^4.3.0
  cloud_firestore: ^6.1.1
  flutter_staggered_grid_view: ^0.7.0
  google_nav_bar: ^5.0.7
  shared_preferences: ^2.5.4
  palette_generator: ^0.3.3+7
  firebase_storage: ^13.0.5
  firebase_auth: ^6.1.3
  google_sign_in: 6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
